export const ON_WAYPOINT_EVENT = 'ON_WAYPOINT_EVENT';
export const ON_MENU_TOGGLE = 'ON_MENU_TOGGLE';
export const ON_OPEN_PROJECT_DETAILS = 'ON_OPEN_PROJECT_DETAILS';
export const ON_CLOSE_PROJECT_DETAILS = 'ON_CLOSE_PROJECT_DETAILS';